grid = [
    {
        "name": "baseline_final",
        "config": {
            "optimizer": "adamw",
            "lr_ft": 0.00015,
            "lr_head": 0.003,
            "weight_decay_head": 0.00005,
            "weight_decay_ft": 0.0007,
            "epochs_head": 12,
            "epochs_ft": 12,
            "patience_head": 2,
            "patience_ft": 2,
            "dropout_p": 0.3,
            "ft_trainable_attrs": None,  # fine-tune all layers
            "label_smoothing": 0.0,
            "use_cosine_schedule": False,
        },
    },
    {
        "name": "ft_wd_up",
        "config": {
            "optimizer": "adamw",
            "lr_ft": 0.00015,
            "lr_head": 0.003,
            "weight_decay_head": 0.00005,
            "weight_decay_ft": 0.0010,
            "epochs_head": 12,
            "epochs_ft": 12,
            "patience_head": 2,
            "patience_ft": 2,
            "dropout_p": 0.3,
            "ft_trainable_attrs": None,
            "label_smoothing": 0.0,
            "use_cosine_schedule": False,
        },
    },
    {
        "name": "ft_lr_down",
        "config": {
            "optimizer": "adamw",
            "lr_ft": 0.00010,
            "lr_head": 0.003,
            "weight_decay_head": 0.00005,
            "weight_decay_ft": 0.0007,
            "epochs_head": 12,
            "epochs_ft": 12,
            "patience_head": 2,
            "patience_ft": 2,
            "dropout_p": 0.3,
            "ft_trainable_attrs": None,
            "label_smoothing": 0.0,
            "use_cosine_schedule": False,
        },
    },
    {
        "name": "partial_ft_l3_l4_fc",
        "config": {
            "optimizer": "adamw",
            "lr_ft": 0.00015,
            "lr_head": 0.003,
            "weight_decay_head": 0.00005,
            "weight_decay_ft": 0.0007,
            "epochs_head": 12,
            "epochs_ft": 12,
            "patience_head": 2,
            "patience_ft": 2,
            "dropout_p": 0.3,
            "ft_trainable_attrs": ["layer3", "layer4", "fc"],
            "label_smoothing": 0.0,
            "use_cosine_schedule": False,
        },
    },
    {
        "name": "dropout_up",
        "config": {
            "optimizer": "adamw",
            "lr_ft": 0.00015,
            "lr_head": 0.003,
            "weight_decay_head": 0.00005,
            "weight_decay_ft": 0.0007,
            "epochs_head": 12,
            "epochs_ft": 12,
            "patience_head": 2,
            "patience_ft": 2,
            "dropout_p": 0.5,
            "ft_trainable_attrs": None,
            "label_smoothing": 0.0,
            "use_cosine_schedule": False,
        },
    },
    {
        "name": "shorter_ft_epochs",
        "config": {
            "optimizer": "adamw",
            "lr_ft": 0.00015,
            "lr_head": 0.003,
            "weight_decay_head": 0.00005,
            "weight_decay_ft": 0.0007,
            "epochs_head": 12,
            "epochs_ft": 8,
            "patience_head": 2,
            "patience_ft": 2,
            "dropout_p": 0.3,
            "ft_trainable_attrs": None,
            "label_smoothing": 0.0,
            "use_cosine_schedule": False,
        },
    },
    {
        "name": "higher_head_wd",
        "config": {
            "optimizer": "adamw",
            "lr_ft": 0.00015,
            "lr_head": 0.003,
            "weight_decay_head": 0.00010,
            "weight_decay_ft": 0.0007,
            "epochs_head": 12,
            "epochs_ft": 12,
            "patience_head": 2,
            "patience_ft": 2,
            "dropout_p": 0.3,
            "ft_trainable_attrs": None,
            "label_smoothing": 0.0,
            "use_cosine_schedule": False,
        },
    },
    {
        "name": "lower_head_lr",
        "config": {
            "optimizer": "adamw",
            "lr_ft": 0.00015,
            "lr_head": 0.0015,
            "weight_decay_head": 0.00005,
            "weight_decay_ft": 0.0007,
            "epochs_head": 12,
            "epochs_ft": 12,
            "patience_head": 2,
            "patience_ft": 2,
            "dropout_p": 0.3,
            "ft_trainable_attrs": None,
            "label_smoothing": 0.0,
            "use_cosine_schedule": False,
        },
    },
    {
        "name": "higher_ft_lr",
        "config": {
            "optimizer": "adamw",
            "lr_ft": 0.00020,
            "lr_head": 0.003,
            "weight_decay_head": 0.00005,
            "weight_decay_ft": 0.0007,
            "epochs_head": 12,
            "epochs_ft": 12,
            "patience_head": 2,
            "patience_ft": 2,
            "dropout_p": 0.3,
            "ft_trainable_attrs": None,
            "label_smoothing": 0.0,
            "use_cosine_schedule": False,
        },
    },
    {
        "name": "partial_ft_layer4_fc_only",
        "config": {
            "optimizer": "adamw",
            "lr_ft": 0.00015,
            "lr_head": 0.003,
            "weight_decay_head": 0.00005,
            "weight_decay_ft": 0.0010,
            "epochs_head": 12,
            "epochs_ft": 12,
            "patience_head": 2,
            "patience_ft": 2,
            "dropout_p": 0.4,
            "ft_trainable_attrs": ["layer4", "fc"],
            "label_smoothing": 0.0,
            "use_cosine_schedule": False,
        },
    },
]
